Update lib/cli-table/utils.js
Because of error

```/root/tok/node_modules/alfred/node_modules/step/lib/step.js:39
        throw arguments[0];
                       ^
TypeError: Cannot use 'in' operator to search for 'chars' in undefined
    at Object.exports.options (/root/tok/node_modules/cli-table/lib/cli-table/utils.js:78:36)
```